# Site settings
title: 董云达的个人主页
description: 'Business Card Page'
url: 'ydong2024.github.io'
baseurl: ''
profilepic: '/images/DongYunda.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'https://cdn.bootcdn.net/ajax/libs/font-awesome/6.5.2/js/fontawesome.min.js'

author:
  name: '董云达'
  email: ydong@zzu.edu.cn
#  mastodon: tzuehlke@mstdn.social
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
#  github_username:  tzuehlke
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
